version: "2.4"

volumes:
  mongo_data:

services:
  mongo:
    image: mongo:4.2.5-bionic
    container_name: blog_mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - "./docker/mongo/:/docker-entrypoint-initdb.d"
    env_file:
      - .env.prod

  api:
    build:
      context: .
      target: prod_api
      dockerfile: ./Dockerfile
    container_name: blog_prod_api
    ports:
      - '3333:3333'
    volumes:
    - ./.env.prod:/myapp/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      target: prod_frontend
      dockerfile: ./Dockerfile
    container_name: blog_prod_frontend
    ports:
      - '80:80'
    volumes:
      - ./docker/frontend/prod/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
